/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#include "../brick_game/tetris/backend.h"
#include "../brick_game/tetris/fsm.h"
#include "../brick_game/tetris/tetris_lib.h"

START_TEST(test_input) {
  start_game();
  all_parameters* get_all_parameters = getting_all_parameters();

  user_input_1('\n');
  ck_assert_int_eq(game_status(), 1);

  user_input_1(32);
  ck_assert_int_eq(get_all_parameters->game_parametrs.pause, -1);

  user_input_1(27);
  ck_assert_int_eq(get_all_parameters->GAME_STATUS, GAME_OVER);

  user_input_2(KEY_LEFT);
  ck_assert_int_eq(get_all_parameters->figure_parameters.x, 2);

  user_input_2(KEY_RIGHT);
  ck_assert_int_eq(get_all_parameters->figure_parameters.x, 3);

  user_input_2(KEY_UP);
  ck_assert_int_eq(get_all_parameters->fall_status, 0);

  user_input_2(KEY_DOWN);
  ck_assert_int_eq(get_all_parameters->fall_status, 1);

  initialize_figure(get_all_parameters->figure_parameters.arr, 1);
  int pattern1[5][5] = {{0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0},
                        {1, 1, 1, 1, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern1[i][j]);
    }
  }
  user_input_2('w');
  int pattern2[5][5] = {{0, 0, 0, 0, 0},
                        {0, 0, 1, 0, 0},
                        {0, 0, 1, 0, 0},
                        {0, 0, 1, 0, 0},
                        {0, 0, 1, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern2[i][j]);
    }
  }

  user_input_2('/');
  ck_assert_int_eq(get_all_parameters->figure_parameters.y, 15);

  end_game();
}
END_TEST

START_TEST(test_move) {
  start_game();

  while (game_status() == GAME_IS_ON) {
    all_parameters* get_all_parameters = getting_all_parameters();
    timer_for_fall(get_all_parameters);
    user_input_2(KEY_DOWN);
    movement(get_all_parameters);
  }
  GameInfo_t info_for_field = updateCurrentState();
  ck_assert_int_eq(info_for_field.level, 1);
  ck_assert_int_eq(info_for_field.speed, 1);
  ck_assert_int_eq(info_for_field.pause, 1);
  ck_assert_int_eq(info_for_field.score, 0);
  ck_assert_int_eq(game_status(), GAME_OVER);

  end_game();
}
END_TEST

START_TEST(test_initialize_figure) {
  start_game();
  all_parameters* get_all_parameters = getting_all_parameters();
  initialize_figure(get_all_parameters->figure_parameters.arr, 1);
  int pattern1[5][5] = {{0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0},
                        {1, 1, 1, 1, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern1[i][j]);
    }
  }
  initialize_figure(get_all_parameters->figure_parameters.arr, 2);
  int pattern2[5][5] = {{0, 0, 0, 0, 0},
                        {0, 1, 0, 0, 0},
                        {0, 1, 1, 1, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern2[i][j]);
    }
  }
  initialize_figure(get_all_parameters->figure_parameters.arr, 3);
  int pattern3[5][5] = {{0, 0, 0, 0, 0},
                        {0, 0, 0, 1, 0},
                        {0, 1, 1, 1, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern3[i][j]);
    }
  }
  initialize_figure(get_all_parameters->figure_parameters.arr, 4);
  int pattern4[5][5] = {{0, 0, 0, 0, 0},
                        {0, 1, 1, 0, 0},
                        {0, 1, 1, 0, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern4[i][j]);
    }
  }
  initialize_figure(get_all_parameters->figure_parameters.arr, 5);
  int pattern5[5][5] = {{0, 0, 0, 0, 0},
                        {0, 0, 1, 1, 0},
                        {0, 1, 1, 0, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern5[i][j]);
    }
  }
  initialize_figure(get_all_parameters->figure_parameters.arr, 6);
  int pattern6[5][5] = {{0, 0, 0, 0, 0},
                        {0, 0, 1, 0, 0},
                        {0, 1, 1, 1, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern6[i][j]);
    }
  }
  initialize_figure(get_all_parameters->figure_parameters.arr, 7);
  int pattern7[5][5] = {{0, 0, 0, 0, 0},
                        {0, 1, 1, 0, 0},
                        {0, 0, 1, 1, 0},
                        {0, 0, 0, 0, 0},
                        {0, 0, 0, 0, 0}};
  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      ck_assert_int_eq(get_all_parameters->figure_parameters.arr[i][j],
                       pattern7[i][j]);
    }
  }
  end_game();
}
END_TEST

START_TEST(test_check_attaching) {
  start_game();
  all_parameters* get_all_parameters = getting_all_parameters();
  figure_right(get_all_parameters);
  figure_right(get_all_parameters);
  figure_right(get_all_parameters);
  figure_right(get_all_parameters);
  get_all_parameters->figure_parameters.x = 3;
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  get_all_parameters->figure_parameters.x = 3;
  initialize_figure(get_all_parameters->figure_parameters.arr, 1);
  user_input_2('w');
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  figure_left(get_all_parameters);
  user_input_2('w');
  end_game();
}
END_TEST

START_TEST(test_fall_new_figure) {
  start_game();
  all_parameters* get_all_parameters = getting_all_parameters();
  get_all_parameters->next_pattern_num = 1;
  fall_new_figure(get_all_parameters);
  end_game();
}
END_TEST

START_TEST(test_clean_filled_lines) {
  start_game();
  all_parameters* get_all_parameters = getting_all_parameters();

  for (int j = 0; j < WIDTH; j++) {
    get_all_parameters->game_parametrs.field[19][j] = 1;
  }

  clean_filled_lines(get_all_parameters);
  ck_assert_int_eq(get_all_parameters->game_parametrs.score, 100);

  for (int j = 0; j < WIDTH; j++) {
    get_all_parameters->game_parametrs.field[19][j] = 1;
  }
  for (int j = 0; j < WIDTH; j++) {
    get_all_parameters->game_parametrs.field[18][j] = 1;
  }
  clean_filled_lines(get_all_parameters);
  ck_assert_int_eq(get_all_parameters->game_parametrs.score, 400);

  end_game();
}
END_TEST

int main(void) {
  Suite* s1 = suite_create("Core");
  TCase* tc1_1 = tcase_create("Core");
  SRunner* sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_input);
  tcase_add_test(tc1_1, test_move);
  tcase_add_test(tc1_1, test_initialize_figure);
  tcase_add_test(tc1_1, test_check_attaching);
  tcase_add_test(tc1_1, test_fall_new_figure);
  tcase_add_test(tc1_1, test_clean_filled_lines);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
